global:
  scrape_interval: 2s
  evaluation_interval: 2s
scrape_configs:
  - job_name: 'prometheusJob'
    scrape_interval: 2s
    static_configs:
      - targets: ['localhost:9090'] #Servidor prometheus
  - job_name: 'demo-app'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.0.16:8081'] #Servidor da minha aplicação
